Repository SeongTeam/ggrim-back-main, pull requests merged in 2025-02, with the labels that each got.

#1 Config ci
  .github/workflows/deploy-docker-image.yml
  .github/workflows/deploy-to-cloudtype.yml
  Dockerfile
  README.md
Labels: ci/cd

#8 Chore/add search title colum to painting
  migration/README.md
  migration/action/1739861168490-addSearchColumToPatinting.ts
  migration/action/1739865206420-update_searchTitle_ToPainting.ts
  migration_action.js
  package-lock.json
  package.json
Labels: chore

#10 Feat/replace field in search query
  migration/README.md
  migration/action/1739861168490-addSearchColumToPatinting.ts
  migration/action/1739865206420-update_searchTitle_ToPainting.ts
  migration_action.js
  package-lock.json
  package.json
  src/painting/entities/painting.entity.ts
  src/painting/painting.service.ts
Labels: Feature

#14 chore:update package-lock.json
  package-lock.json
Labels: chore, fix
