Repository SeongTeam/ggrim-back-main, pull requests merged in 2025-03, with the labels that each got.

#11 Feat/add painting in to artwork of week api
  app-config/artwork_of_week_default.json
  src/painting/dto/output/weekly-art.dto.ts
  src/painting/painting.controller.ts
  src/painting/painting.service.ts
Labels: Feature, chore

#16 Feat/standardize array format for get api query
  src/painting/dto/search-painting.dto.ts
  src/painting/painting.controller.spec.ts
  src/painting/painting.service.ts
  test/e2e/painting.e2e-spec.ts
Labels: Feature

#18 Chore/edit docs
  README.md
  app-config/artwork_of_week_default.json
  src/app.module.ts
  src/painting/entities/painting.entity.ts
  src/painting/painting.controller.ts
  src/painting/painting.module.ts
  src/painting/painting.service.ts
  src/quiz/entities/quiz.entity.ts
  src/quiz/quiz.controller.ts
  src/quiz/quiz.service.ts
  src/style/dto/create-style.dto.ts
  src/style/dto/replace-style.dto.ts
  src/style/entities/style.entity.ts
  src/style/style.controller.ts
  src/style/style.module.ts
  src/style/style.service.ts
  src/tag/dto/create-tag.dto.ts
  src/tag/dto/replace-tag.dto.ts
  src/tag/dto/search-tag.dto.ts
  src/tag/entities/tag.entity.ts
  src/tag/tag.controller.ts
  src/tag/tag.modue.ts
  src/tag/tag.service.ts
Labels: documentation, Refactor

#22 Feat/quiz schedule
  app-config/artwork_of_week_default.json
  package-lock.json
  package.json
  src/Logger/logger.service.ts
  src/main.ts
  src/painting/painting.controller.ts
  src/painting/painting.service.ts
  src/quiz/dto/output/response-schedule-quiz.dto.ts
  src/quiz/dto/quiz-context.dto.ts
  src/quiz/dto/schedule-quiz.query.dto.ts
  src/quiz/interface/quiz-context.ts
  src/quiz/interface/quiz-status.ts
  src/quiz/quiz-schedule.service.ts
  src/quiz/quiz.controller.ts
  src/quiz/quiz.module.ts
Labels: Feature
